name: Build
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.6
        - 3.7
        - 3.8
        - 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    - name: Lint with pylint
      run: pylint buildrunner
    - name: Test with pytest
      run: pytest --junitxml=test-reports/test-results.xml
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: github.event_name == 'push' && always()
      with:
        files: test-reports/test-results.xml
        check_name: "Test Results ${{ matrix.python-version }}"
  publish-pypi:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install wheel
      run: pip install wheel
    - name: Build
      run: python setup.py sdist bdist_wheel
    - name: Check upload
      run: pip install twine && twine check dist/*
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
      # Skips publishing on forks/pull requests
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'adobe/buildrunner'
      with:
        user: __token__
        password: ${{ secrets.ADOBE_BOT_PYPI_TOKEN }}
  publish-docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Docker Tags
      id: docker_tags
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/adobe/buildrunner
    # Buildx is used to build multi-platform images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # The build-push-action automatically authenticates using the GITHUB_TOKEN
    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        # Only push if this a tagged version
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'adobe/buildrunner' }}
        platforms: linux/amd64,linux/arm64
        # Always include latest tag
        flavor: |
          latest=true
        tags: ${{ steps.docker_tags.outputs.tags }}
        labels: ${{ steps.docker_tags.outputs.labels }}
